version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name kadai5teamC2 --s3-location s3://kadai520250819/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src